# Pipeline settings you can tweak without editing code
dashboard_title: "AI Pipeline Demo"
clusters: 4
mesh:
  type: "torus"          # torus | sphere | file
  R: 3.0                 # torus major radius
  r: 1.0                 # torus minor radius
  nu: 100                # torus u resolution
  nv: 80                 # torus v resolution
  file_path: ""          # used when type: file (path under data/ or URL)
metrics_days: 30
seed: 42
