# 1) Make sure folders exist
mkdir -p .github/workflows docs

# 2) Create the workflow file with a heredoc
cat > .github/workflows/build.yml <<'YAML'
name: build-dashboard

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * *'   # daily at 06:00 UTC

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline (generate HTML)
        run: python pipeline/generate_dashboard.py

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add -A
            git commit -m "chore: update dashboard [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
YAML

# 3) Make sure Pages serves static files as-is
:> docs/.nojekyll
